### ISSUE TITLE
data not batched

### ISSUE THREAD

**Issue by EParisot** [zhangzp9970/MIA#2]
Hi and thank you for publishing your work !
I noticed batch_size is not used in training procedure, I tryed your code without success, on MNIST with only FC layers model...

**Comment by zhangzp9970** [comment]
Sorry for the late reply. The batch size is used in main.py but not used in attack.py. Because one image that represent the class is reconstructed each time. You can refer to the original paper for more details. 
The code runs successfully on my computer, could you please provide more details of the error?

**Comment by EParisot** [comment]
Thank you very much, I thought the main.py was just about training the target model, so I just used another one, I'll start by running your full implementation and see what happens before I try to attack my own model.
Thank you again !
